In [49]:
!pip install mlflow

Requirement already satisfied: mlflow in /usr/local/lib/python3.13/dist-packages (3.15.2)
Requirement already satisfied: mlflow-skinny==3.15.2 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.15.2)
Requirement already satisfied: mlflow-tracing==3.15.2 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.15.2)
Requirement already satisfied: Flask-CORS<7 in /usr/local/lib/python3.13/dist-packages (from mlflow) (6.0.5)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4,>=3.7.0 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.14.3)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.13/dist-packages (from mlflow) (1.19.1)
Requirement already satisfied: cryptography<50,>=43.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow) (49.0.0)
Requirement already satisfied: docker<8,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow) (7.2.0)
Requirement already satisfied: graphene<4 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.4.3)
Requirement already satisfied: gunicorn<27 in /usr/local/lib/python3.13/dist-packages (from mlflow) (26.2.0)
Requirement already satisfied: huey<4,>=2.5.4 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.3.4)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.13/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.13/dist-packages (from mlflow) (2.1.3)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.13/dist-packages (from mlflow) (2.2.3)
Requirement already satisfied: pyarrow<26,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.13/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.13/dist-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in /usr/local/lib/python3.13/dist-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from mlflow) (2.0.52)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (8.4.2)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (3.1.2)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (0.133.0)
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (0.141.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (3.1.60)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (9.0.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (1.42.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (1.44.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (1.42.1)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (26.3)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (2.13.4)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (1.2.3)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (0.6.0)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (1.6.0)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (4.16.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.13/dist-packages (from mlflow-skinny==3.15.2->mlflow) (0.52.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp<4,>=3.7.0->mlflow) (1.24.5)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.1.3)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from cryptography<50,>=43.0.0->mlflow) (2.1.1)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from Flask<4->mlflow) (3.1.8)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /usr/local/lib/python3.13/dist-packages (from graphene<4->mlflow) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /usr/local/lib/python3.13/dist-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.13/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas<3->mlflow) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.13/dist-packages (from skops<1->mlflow) (3.18.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->cryptography<50,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.13/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.2->mlflow) (2.49.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from fastapi<1->mlflow-skinny==3.15.2->mlflow) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from fastapi<1->mlflow-skinny==3.15.2->mlflow) (0.0.5)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.15.2->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.13/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.15.2->mlflow) (4.1.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in /usr/local/lib/python3.13/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.15.2->mlflow) (0.63b1)
Requirement already satisfied: wcwidth>=0.3.5 in /usr/local/lib/python3.13/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.2->mlflow) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.15.2->mlflow) (2.46.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.2->mlflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.2->mlflow) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.15.2->mlflow) (2026.7.22)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.13/dist-packages (from starlette<2->mlflow-skinny==3.15.2->mlflow) (4.14.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn<1->mlflow-skinny==3.15.2->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.13/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.15.2->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.2->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.13/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.2->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.13/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.15.2->mlflow) (0.6.4)

In [50]:
pip install dagshub

Requirement already satisfied: dagshub in /usr/local/lib/python3.13/dist-packages (0.7.1)
Requirement already satisfied: PyYAML>=5 in /usr/local/lib/python3.13/dist-packages (from dagshub) (6.0.3)
Requirement already satisfied: appdirs>=1.4.4 in /usr/local/lib/python3.13/dist-packages (from dagshub) (1.4.4)
Requirement already satisfied: click>=8.0.4 in /usr/local/lib/python3.13/dist-packages (from dagshub) (8.4.2)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from dagshub) (0.28.1)
Requirement already satisfied: GitPython>=3.1.29 in /usr/local/lib/python3.13/dist-packages (from dagshub) (3.1.60)
Requirement already satisfied: rich>=13.1.0 in /usr/local/lib/python3.13/dist-packages (from dagshub) (13.9.4)
Requirement already satisfied: dacite~=1.6.0 in /usr/local/lib/python3.13/dist-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in /usr/local/lib/python3.13/dist-packages (from dagshub) (9.1.4)
Requirement already satisfied: gql[requests] in /usr/local/lib/python3.13/dist-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in /usr/local/lib/python3.13/dist-packages (from dagshub) (0.6.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from dagshub) (2.2.3)
Requirement already satisfied: treelib>=1.6.4 in /usr/local/lib/python3.13/dist-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from dagshub) (3.3.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.13/dist-packages (from dagshub) (2.9.0.post0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.13/dist-packages (from dagshub) (1.43.80)
Requirement already satisfied: semver in /usr/local/lib/python3.13/dist-packages (from dagshub) (3.0.4)
Requirement already satisfied: dagshub-annotation-converter>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from dagshub) (0.2.2)
Requirement already satisfied: lxml in /usr/local/lib/python3.13/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (6.1.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (11.3.0)
Requirement already satisfied: pydantic>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (2.13.4)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.13/dist-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (4.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.13/dist-packages (from GitPython>=3.1.29->dagshub) (4.0.12)
Requirement already satisfied: anyio in /usr/local/lib/python3.13/dist-packages (from httpx>=0.23.0->dagshub) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx>=0.23.0->dagshub) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.13/dist-packages (from httpx>=0.23.0->dagshub) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx>=0.23.0->dagshub) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.1.0->dagshub) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.1.0->dagshub) (2.21.0)
Requirement already satisfied: six>=1.13.0 in /usr/local/lib/python3.13/dist-packages (from treelib>=1.6.4->dagshub) (1.17.0)
Requirement already satisfied: botocore<1.44.0,>=1.43.80 in /usr/local/lib/python3.13/dist-packages (from boto3->dagshub) (1.43.80)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.13/dist-packages (from boto3->dagshub) (1.1.0)
Requirement already satisfied: s3transfer<0.20.0,>=0.19.0 in /usr/local/lib/python3.13/dist-packages (from boto3->dagshub) (0.19.2)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.13/dist-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.13/dist-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: graphql-core<3.3,>=3.2 in /usr/local/lib/python3.13/dist-packages (from gql[requests]->dagshub) (3.2.11)
Requirement already satisfied: yarl<2.0,>=1.6 in /usr/local/lib/python3.13/dist-packages (from gql[requests]->dagshub) (1.24.5)
Requirement already satisfied: backoff<3.0,>=1.11.1 in /usr/local/lib/python3.13/dist-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests<3,>=2.26 in /usr/local/lib/python3.13/dist-packages (from gql[requests]->dagshub) (2.32.4)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from gql[requests]->dagshub) (1.0.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas->dagshub) (2.1.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->dagshub) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->dagshub) (2026.3)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /usr/local/lib/python3.13/dist-packages (from botocore<1.44.0,>=1.43.80->boto3->dagshub) (2.5.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.13/dist-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.29->dagshub) (5.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.2)
Requirement already satisfied: packaging>=17.0 in /usr/local/lib/python3.13/dist-packages (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->dagshub) (26.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.2.0->dagshub) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.2.0->dagshub) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.0.0->dagshub-annotation-converter>=0.2.0->dagshub) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.26->gql[requests]->dagshub) (3.4.9)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.1.0)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.13/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (6.7.1)
Requirement already satisfied: propcache>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from yarl<2.0,>=1.6->gql[requests]->dagshub) (0.5.2)

In [51]:
import dagshub
dagshub.init(repo_owner='balaram.sahu8', repo_name='YT-Sentiment-analysis', mlflow=True)

import mlflow
with mlflow.start_run():
  mlflow.log_param('parameter name', 'value')
  mlflow.log_metric('metric name', 1)

Initialized MLflow to track repo "balaram.sahu8/YT-Sentiment-analysis"

Repository balaram.sahu8/YT-Sentiment-analysis initialized!

🏃 View run nervous-worm-118 at: https://dagshub.com/balaram.sahu8/YT-Sentiment-analysis.mlflow/#/experiments/1/runs/fb31103dba3347678b3853623772aa2b
🧪 View experiment at: https://dagshub.com/balaram.sahu8/YT-Sentiment-analysis.mlflow/#/experiments/1

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [53]:
df = pd.read_csv('https://raw.githubusercontent.com/Himanshu-1703/reddit-sentiment-analysis/refs/heads/main/data/reddit.csv')
df.head()

                                       clean_comment  category
0   family mormon have never tried explain them t...         1
1  buddhism has very much lot compatible with chr...         1
2  seriously don say thing first all they won get...        -1
3  what you have learned yours and only yours wha...         0
4  for your own benefit you may want read living ...         1

In [54]:
df.isnull().sum()

clean_comment    100
category           0
dtype: int64

In [55]:
df[df['clean_comment'].isna()]

      clean_comment  category
413             NaN         0
605             NaN         0
2422            NaN         0
2877            NaN         0
3307            NaN         0
...             ...       ...
35975           NaN         0
36036           NaN         0
37043           NaN         0
37111           NaN         0
37238           NaN         0

[100 rows x 2 columns]

In [56]:
df.dropna(inplace=True)

In [57]:
df.isnull().sum()

clean_comment    0
category         0
dtype: int64

In [58]:
df.duplicated().sum()

np.int64(350)

In [59]:
df[df.duplicated()]

                                           clean_comment  category
375                                                              0
392                                                              0
617                                           aurum mom          0
651                                                              0
1222                                                             0
...                                                  ...       ...
36915                                           who won          0
37044                                                            0
37125                                              hari          0
37158                                           top kek          1
37234  this part series minute videos focusing each d...         1

[350 rows x 2 columns]

In [60]:
df.drop_duplicates(inplace=True,keep='first')

In [61]:
df.shape

(36799, 2)

In [62]:
df.duplicated().sum()

np.int64(0)

In [63]:
pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk) (4.67.3)

In [64]:
import re
import string
import nltk

from nltk.corpus import stopwords, wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Download once
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("wordnet")
nltk.download("stopwords")
nltk.download("omw-1.4")

# Initialize
lemmatizer = WordNetLemmatizer()

# Stopwords
stop_words = set(stopwords.words("english"))

# Words that should NOT be removed
keep_words = {
    "not", "no", "there", "but", "however", "yet"
}

stop_words = stop_words - keep_words


def preprocess_text(text):
    """
    Clean and preprocess text:
    1. Convert to lowercase
    2. Remove HTML tags
    3. Remove URLs
    4. Remove email addresses
    5. Remove numbers
    6. Remove punctuation and special characters
    7. Remove \\n and \\r
    8. Remove stopwords except selected words
    9. WordNet lemmatization
    """

   # 1. Convert to lowercase
    text = text.lower()

    # 2. Remove \n and \r
    text = re.sub(r"[\n\r]+", " ", text)

    # 3. Remove HTML tags
    text = re.sub(r"<[^>]+>", " ", text)

    # 4. Remove URLs
    text = re.sub(r"https?://\S+|www\.\S+", " ", text)

    # 5. Remove email addresses
    text = re.sub(r"\S+@\S+", " ", text)

    # 6. Remove numbers
    text = re.sub(r"\d+", " ", text)

    # 7. Remove punctuation and special characters
    # Keep only alphabets and whitespace
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # 8. Remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()

    # 9. Tokenization
    words = word_tokenize(text)

    # 10. Remove stopwords
    words = [
        word for word in words
        if word not in stop_words
    ]

    # 11. WordNet lemmatization
    words = [
        lemmatizer.lemmatize(word)
        for word in words
    ]

    # 12. Join words back into sentence
    return " ".join(words)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [65]:
df['clean_comment'] = df['clean_comment'].apply(preprocess_text)

In [66]:
df['clean_comment'][0]

'family mormon never tried explain still stare puzzled time time like kind strange creature nonetheless come admire patience calmness equanimity acceptance compassion developed thing buddhism teach'

In [67]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [68]:
x = CountVectorizer(max_features=10000).fit_transform(df['clean_comment']).toarray()
y = df['category']

In [69]:
x.shape

(36799, 10000)

In [70]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [71]:
mlflow.set_tracking_uri("https://dagshub.com/balaram.sahu8/YT-Sentiment-analysis.mlflow")
mlflow.set_experiment("YT-Sentiment-analysis-RF-Basemodel")

# Re-import classification_report and confusion_matrix to ensure correct function reference
from sklearn.metrics import classification_report, confusion_matrix

with mlflow.start_run() as run:
    # Log a description for the run
    mlflow.set_tag("mlflow.runName", "RandomForest_Baseline_TrainTestSplit")
    mlflow.set_tag("experiment_type", "baseline")
    mlflow.set_tag("model_type", "RandomForestClassifier")

    # Add a description
    mlflow.set_tag("description", "Baseline RandomForest model for sentiment analysis using Bag of Words (BoW) with a simple train-test split")

    # Log parameters for the vectorizer
    mlflow.log_param("vectorizer_type", "CountVectorizer")
    mlflow.log_param("vectorizer_max_features", 10000)

    # Log Random Forest parameters
    n_estimators = 200
    max_depth = 15

    mlflow.log_param("n_estimators", n_estimators)
    mlflow.log_param("max_depth", max_depth)

    # Initialize and train the model
    model = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, random_state=42)
    model.fit(x_train, y_train)

    # Make predictions on the test set
    y_pred = model.predict(x_test)

    # Log metrics for each class and accuracy
    accuracy = accuracy_score(y_test, y_pred)
    mlflow.log_metric("accuracy", accuracy)

    # Get classification report as dictionary for individual metrics and as string for text log
    clf_report_dict = classification_report(y_test, y_pred, output_dict=True)
    clf_report_text = classification_report(y_test, y_pred)
    mlflow.log_text(clf_report_text, "classification_report.txt")

    for label, metrics in clf_report_dict.items():
        if isinstance(metrics, dict):  # For precision, recall, f1-score, etc.
            for metric, value in metrics.items():
                mlflow.log_metric(f"{label}_{metric}", value)

    # Confusion matrix plot
    conf_matrix_data = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(conf_matrix_data, annot=True, fmt="d", cmap="Blues")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.title("Confusion Matrix")

    # Save and log the confusion matrix plot
    plt.savefig("confusion_matrix.png")
    plt.close() # Close the plot to free up memory
    mlflow.log_artifact("/content/confusion_matrix.png")

    # Log the Random Forest model
    mlflow.sklearn.log_model(model, "random_forest_model")

    # Optionally log the dataset itself (if it's small enough)
    df.to_csv("dataset.csv", index=False)
    mlflow.log_artifact("/content/dataset.csv")

# Display final accuracy
print(f"Accuracy: {accuracy}")

2026/08/26 11:48:52 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

🏃 View run RandomForest_Baseline_TrainTestSplit at: https://dagshub.com/balaram.sahu8/YT-Sentiment-analysis.mlflow/#/experiments/1/runs/459dec4b15de4c5c97c310b0b6d1d4e2
🧪 View experiment at: https://dagshub.com/balaram.sahu8/YT-Sentiment-analysis.mlflow/#/experiments/1
Accuracy: 0.6501358695652174

In [72]:
clf_report = classification_report(y_test, y_pred)
print(clf_report)

              precision    recall  f1-score   support

          -1       1.00      0.02      0.03      1651
           0       0.68      0.82      0.74      2509
           1       0.63      0.85      0.72      3200

    accuracy                           0.65      7360
   macro avg       0.77      0.56      0.50      7360
weighted avg       0.73      0.65      0.57      7360

In [73]:
print(conf_matrix_data)

[[  26  494 1131]
 [   0 2048  461]
 [   0  489 2711]]

In [74]:
# if we will see here relacall is very low means out of 1651 data points only -1 classified 26 data points
# accuracy 1 beacuse there TP 26/26+0+0 = 1

# because of imbalane dataset issue we are getting low accuracy we have to do data balance

In [75]:
df.to_csv('cleand_df.csv',index=False)